routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/tabla-amortizacion/{clienteId}', 'TablaAmortizacionController@index')->name('tabla-amortizacion')->middleware('auth');

Route::prefix('catalogos')->group(function () {
    Route::get('/product', 'ProductController@index')->name('product-list');

    Route::resource('oficina', 'OficinaController')->middleware('auth');
    Route::resource('user', 'UserController')->middleware('auth');
    //Route::resource('user', 'UserController')->except(['create', 'edit'])->middleware('auth');
    //Route::resource('user', 'UserController')->only(['destroy', 'create'])->middleware('auth');
});

// user.index => "Listado de registros"

// user.create => "Mostrar pantalla de nuevo registro"
// user.store => "Guardado de nuevo registro"

// user.edit => "Mostrar pantalla de registro existente"
// user.update => "Actualizar registro existente"

// user.destroy => "Eliminar registro existente"

// user.show => "Mostrar información de registro existente"

app/Oficina.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Oficina extends Model
{
    //
}

app/Http/Controllers/OficinaController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Oficina;
use Illuminate\Http\Request;

class OficinaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oficinas = Oficina::all();

        return view('Oficina.index')->with(['oficinas' => $oficinas, 'title' => 'Listado de Oficinas del sistema', 'user_name' => session('user_name')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Auth::user()->hasRole('owner')) {
            return redirect()->route('oficina.index');
        }
        return view('Oficina.create')->with('title', 'Crear nueva oficina');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $oficinaNueva          = new Oficina;
        $oficinaNueva->name    = $request->input('name');
        $oficinaNueva->name    = $request->name;
        $oficinaNueva->address = $request->get('address');
        $oficinaNueva->phone   = $data['phone'];
        $oficinaNueva->save();

        $request->session()->flash('success', 'El registro de la oficina fue guardado exitosamente !');

        return redirect()->route('oficina.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function show(Oficina $oficina)
    {
        return view('Oficina.show')->with(['oficina' => $oficina, 'title' => 'Registro: ' . $oficina->id . ' de oficinas']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function edit(Oficina $oficina)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Oficina $oficina)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function destroy(Oficina $oficina)
    {
        //
    }
}

resources/views/Oficina/create.blade.php
@extends('Template.main')

@section('table-index')
    <form action="{{ route('oficina.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="form-control">
                <input type="text" name="name" placeholder="Nombre">
            </div>
            <div class="form-control">
                <input type="text" name="address" placeholder="Dirección">
            </div>
            <div class="form-control">
                <input type="text" name="phone" placeholder="Teléfono">
            </div>
        </div>
        <dov class="row">
            <button type="submit" value="Enviar" class="btn btn-success"/>
        </dov>
    </form>

    <a href="{{ route("oficina.index") }}">Regresar</a>
@endsection

resources/views/Oficina/index.blade.php
@extends('Template.main')

@if(count($oficinas))
    @section('table-index')
        {{-- @if(Auth::user()->hasRole('admin')) --}}
        {{-- @if(Entrust::hasRole('admin')) --}}
        @role('owner')
            <a href="{{ route('oficina.create') }}" class="btn btn-info">Nueva oficina</a>
        @endrole

        Usuario: {{ $user_name }}

        <table>
            <tr>
                <td>Nombre</td>
                <td>Domicilio</td>
                <td>Tel&eacute;fono</td>
            </tr>
            @foreach($oficinas as $oficina)
                <tr>
                    <td>{{ $oficina->name }}</td>
                    <td>{{ $oficina->address }}</td>
                    <td>{{ $oficina->phone }}</td>
                </tr>
            @endforeach
        </table>
    @endsection
@endif

resources/views/Oficina/show.blade.php
@extends('Template.main')

@section('table-index')
    <table>
        <tr>
            <td>Nombre</td>
            <td>{{ $oficina->name }}</td>
        </tr>
        <tr>
            <td>Direcci&oacute;n</td>
            <td>{{ $oficina->address }}</td>
        </tr>
        <tr>
            <td>Tel&eacute;fono</td>
            <td>{{ $oficina->phone }}</td>
        </tr>
    </table>

    <a href="{{ route("oficina.index") }}">Regresar</a>
@endsection